#!/bin/bash
# wdaphpdemo post package remove script: remove demo client from auth service config
# WAGO GmbH & Co. KG

AUTH_SERVICE_CLIENT_CONFIG_FILE=/etc/authd/clients/wdaphpdemo.conf

remove_demo_client_to_auth_service_config()
{
	# remove client from folder of known clients
	rm -f "$AUTH_SERVICE_CLIENT_CONFIG_FILE"
	# restart auth service to load new config
	/etc/init.d/authd restart
}

remove_demo_client_to_auth_service_config

exit 0
