#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: update_config
#
# Updates networking configuration of hostname and dns domainname.
# Typically called when configuration data changed by config tools or by
# DHCP/BOOTP.
#
# Author: WAGO GmbH & Co. KG.
#-----------------------------------------------------------------------------#

set -u # error exit on undefined shell variables


function DomainToResolvConf() {
    local validdomain=$1
    local resolvconf=/etc/resolv.conf

    if [ "$validdomain" ]; then
        if [ -s $resolvconf ]; then
            # resolv.conf not empty, can use sed, insert search line
            sed -i -e "1isearch $validdomain" -e "/^search/d" $resolvconf
        else
            # no sed on empty file
            echo "search $validdomain" >$resolvconf
        fi
    else
        # empty domain name, remove any search line in resolv.conf
        sed -i -e "/^search/d" $resolvconf
    fi
}

# main: set global variables
PATH="/bin:/sbin:/usr/bin:/usr/sbin"

validdomain="$(dnsdomainname)"

DomainToResolvConf "$validdomain"

