#!/bin/bash
#-----------------------------------------------------------------------------#
# Script-name: testbacklight
#
# command line parameter: backlight value to test [0..255]
#
# testbacklight backlight preview / test (call it from WBM)
#
# Author: Wolfgang Rückl,  elrest GmbH
#-----------------------------------------------------------------------------#

USESUDO=""

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

paramcount=$#
#echo "paramcount=$paramcount"

if [ $paramcount -lt 1 ]; then
  exit 255
fi

testvalue=$1

if [ $EUID != 0 ]; then
  USESUDO="sudo"
  onvalue=`sudo /usr/bin/setup_display g`
else
  onvalue=`/usr/bin/setup_display g`  
fi


status=$?

if [ $status == 255 ]; then
  exit 255
fi

testtime=`getconfvalue /etc/specific/backlight.conf testbacklight`
status=$?

if [ $status == 255 ]; then
  testtime=2
fi

#stop brightness_control
/etc/config-tools/brightnesscontrol stop > /dev/null 2>&1

$USESUDO /usr/bin/setup_display $testvalue
status=$?

sleep $testtime

$USESUDO /usr/bin/setup_display $onvalue
status=$?

#start brightness_control
/etc/config-tools/brightnesscontrol start > /dev/null 2>&1

exit $status
