#!/bin/sh
#
# /etc/init.d/rcS
#

mount -t proc none /proc

# no kernel messages on the console at runtime
echo "3 4 1 7" > /proc/sys/kernel/printk

if grep -q "quiet" /proc/cmdline; then
        exec 1>/dev/null
fi

echo "mounting filesystems..."
echo ""
mount -a 2>/dev/null
echo "done."

# loadkmap < /etc/boottime.kmap

echo "running rc.d services..."
run-parts -a start /etc/rc.d
