#!/bin/bash

#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2019-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   wdj-ca agent init script
#
# Brief:    Startscript for commissioning agent
#
# Author:   SD,  WAGO GmbH & Co. KG
# Author:   MWW, WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

WDJCA_PIDFILE="/var/run/wdj-ca.pid"

function do_wdjca_start()
{
    echo -n "starting wdj commissioning agent ..."
    start-stop-daemon -S --background --nicelevel 10 --quiet --oknodo --pidfile $WDJCA_PIDFILE --make-pidfile --exec /usr/bin/wdj-ca --
}

function do_wdjca_stop()
{
    echo "stopping wdj commissioning agent ..."
    start-stop-daemon -K --quiet --oknodo --pidfile $WDJCA_PIDFILE --
    rm -f $WDJCA_PIDFILE
}

function usage()
{
    echo "$0 usage: $0 [start|stop|restart]"
}

case $1 in

    start)
        if test -r $WDJCA_PIDFILE && ps -p `cat $WDJCA_PIDFILE` > /dev/null 2>&1; then
            echo "no action done - wdj-ca already running"
            exit 1
        else
            do_wdjca_start
            echo " done"
        fi
        ;;

	stop)
        do_wdjca_stop
        echo " done"
        ;;

    restart)
        do_wdjca_stop
        echo -e "\nwdj commissioning agent stopped, starting again ..."
        do_wdjca_start
        echo " done"
        ;;
    *)
        usage
        ;;
esac
