#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2024 WAGO GmbH & Co. KG

###############################################################
# Adds the localhost as first nameserver if dnsmasq is running.
# This forces dnsmasq to resolve the names. If no result is 
# found the additional nameservers will be used.
#
# If dnsmasq is disabled the localhost will be removed as 
# nameserver.
###############################################################

function AddLocalhostIfDnsmasqIsRunning ()
{
    local LOCAL_NAMESERVER="nameserver 127.0.0.1"
    local RESOLV_CONF=/etc/resolv.conf
    local NET_PARAMS=""

    if [[ -n ${NETCONF_BRIDGE_CONFIG+x} && -n ${NETCONF_IP_CONFIG+x} && -n ${NETCONF_INTERFACE_CONFIG+x} && -n ${NETCONF_INTERFACE_STATUSES+x} ]]; then
        NET_PARAMS="--bridge-config $NETCONF_BRIDGE_CONFIG --ip-config $NETCONF_IP_CONFIG --interface-config $NETCONF_INTERFACE_CONFIG --interface-statuses $NETCONF_INTERFACE_STATUSES"
    fi
    
    local state; state=$(/etc/config-tools/get_dns_service_config -g dns-state "$NET_PARAMS")

    if [ "$state" == "disabled" ]; then
        #remove LOCAL_NAMESERVER
        if grep -q "^$LOCAL_NAMESERVER" $RESOLV_CONF; then
            sed -i -e"/^$LOCAL_NAMESERVER/d" $RESOLV_CONF
            sync
            logger -t DNSMASQ-LOCALHOST "dns support of dnsmasq is disabled - \"$LOCAL_NAMESERVER\" will be removed"
        fi
    else # state == enabled
        #add LOCAL_NAMESERVER before the first nameserver
        if ! grep -q "^$LOCAL_NAMESERVER" $RESOLV_CONF; then
            if grep -q "^nameserver" $RESOLV_CONF; then
                sed -i -e "0,/^nameserver/s//$LOCAL_NAMESERVER\nnameserver/" $RESOLV_CONF
            else
                # no nameserver entries found
                echo "$LOCAL_NAMESERVER" >> $RESOLV_CONF
            fi
            sync
            logger -t DNSMASQ-LOCALHOST "dns support of dnsmasq is enabled - \"$LOCAL_NAMESERVER\" will be added"
        fi
    fi
}

AddLocalhostIfDnsmasqIsRunning
